apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: # enter name of your api image
          env:
          - name: PG_HOST 
            value: postgres
          - name: PG_USER 
            value: postgres
          - name: PG_PASSWORD
            value: postgres_password
          - name: PG_PORT
            value: "5432"
          - name: PG_DATABASE
            value: demo
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
