apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 5173
      targetPort: 5173
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
      app: frontend
  template:
    metadata:
      labels:
        service: frontend
        app: frontend
    spec:
      containers: # image will be retrieved from action and dropped in here
        - name: frontend
          image: 
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
